copyright: Copyright 2024 RISE Security
extra:
  analytics:
    property: G-4Q5VXFWSEK
    provider: google
  generator: false
  homepage: https://risesecurity.com
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/risesecurity
      name: risesecurity on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/risesecurity
      name: risesecurity on LinkedIn
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@risesecurity
      name: risesecurity on Mastodon
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/risesecurity
      name: risesecurity on X
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  # Python Markdown
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Blog:
    - blog/index.md
  - About: about.md
  - Advisories: advisories.md
  - Articles: articles.md
  - Exploits: exploits.md
  - Metasploit:
    - metasploit/index.md
    - metasploit/auxiliary.md
    - metasploit/exploit.md
    - metasploit/payload.md
  - Projects: projects.md
  - Vulnerabilities: vulnerabilities.md
plugins:
  - blog
  - callouts
  - ezlinks
  - glightbox
  - macros:
      include_yaml:
        - advisories: data/advisories.yml
        - articles: data/articles.yml
        - exploits: data/exploits.yml
        - modules: data/modules.yml
        - projects: data/projects.yml
        - vulnerabilities: data/vulnerabilities.yml
  - redirects:
      redirect_maps:
        'index.md': 'blog/index.md'
  # - search
site_name: risesecurity
site_url: https://risesecurity.com
theme:
  custom_dir: overrides
  # favicon: images/favicon.png
  features:
    - navigation.indexes
    - navigation.tabs
  logo: assets/images/logo.png
  name: material
  palette:
    primary: white
