name: pages

on:
  push:
    branches: main

  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Build
        run: |
          pip install mkdocs
          pip install mkdocs-callouts
          pip install mkdocs-ezlinks-plugin
          pip install mkdocs-glightbox
          pip install mkdocs-macros-plugin
          pip install mkdocs-material
          pip install mkdocs-redirects
          mkdocs build

      - name: Setup Tidy
        run: |
          sudo apt update -qq
          sudo apt install -qq tidy

      - name: Run Tidy
        run: find site/ -name "*.html" -type f -exec tidy -config config.txt -m '{}' \;

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    name: Deploy
    needs: build

    permissions:
      id-token: write
      pages: write

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
